services:
    engage360d_security.form.user.post:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_security_post_user", null, { }]
        tags:
            - { name: rest.form, route: post_users }
            - { name: rest.manager, route: post_users }

    engage360d_security.form.security.post.type:
        class: Engage360d\Bundle\SecurityBundle\Form\Type\PostUserFormType
        arguments: [%engage360d_security.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_security_post_user }

    engage360d_security.form.security.put:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_security_put_user", null, { }]
        tags:
            - { name: rest.form, route: put_users }
            - { name: rest.manager, route: put_users }

    engage360d_security.form.security.put.type:
        class: Engage360d\Bundle\SecurityBundle\Form\Type\PutUserFormType
        arguments: [%engage360d_security.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_security_put_user }

    engage360d_security.form.reset_password:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_security_reset_password", null, { }]
        tags:
            - { name: rest.form, route: put_users_reset }

    engage360d_security.form.reset_password.type:
        class: Engage360d\Bundle\SecurityBundle\Form\Type\ResetPasswordFormType
        arguments: [%engage360d_security.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_security_reset_password }
