services:
    engage360d_user.form.user.post:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_user_post_user", null, { }]
        tags:
            - { name: rest.form, route: post_users }
            - { name: rest.manager, route: post_users }

    engage360d_user.form.user.post.type:
        class: Engage360d\Bundle\UserBundle\Form\Type\PostUserFormType
        arguments: [%engage360d_user.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_user_post_user }

    engage360d_user.form.user.put:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_user_put_user", null, { }]
        tags:
            - { name: rest.form, route: put_users }
            - { name: rest.manager, route: put_users }

    engage360d_user.form.user.put.type:
        class: Engage360d\Bundle\UserBundle\Form\Type\PutUserFormType
        arguments: [%engage360d_user.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_user_put_user }
